# Generated by Django 3.2.12 on 2022-04-01 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='document',
            new_name='documento',
        ),
    ]
