# Generated by Django 3.2.12 on 2022-04-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_rename_document_documento_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='documento',
            field=models.FileField(upload_to='documentos/'),
        ),
    ]
